# DevContainer構成用docker-compose

version: '3.6'

services:
    # リバースプロキシサーバー
    nginx:
        image: nginx:1.25.2
        ports:
            - target: 80
              published: 20080
              protocol: tcp
              mode: host
        volumes:
            - type: bind
              source: ./nginx/etc/nginx/nginx.conf
              target: /etc/nginx/nginx.conf
            - type: volume
              source: dev_data_volume
              target: /workspace/data
        depends_on:
            - backend
            - frontend
        restart: "no"

    # フロントエンド用コンテナ
    frontend:
        build:
            context: ../
            dockerfile: .devcontainer/frontend/Dockerfile
        volumes:
            - type: bind 
              source: ../src/frontend/
              target: /src/frontend/
            - type: volume
              source: dev_npm_volume
              target: /src/frontend/node_modules
        tty: true
        depends_on:
            - devcontainer
        restart: "no"

    # バックエンド用コンテナ
    backend:
        build:
            context: ../
            dockerfile: .devcontainer/Dockerfile
            target: backend
        volumes:
            - type: bind 
              source: ../src/backend/
              target: /workspace/src/backend/
            - type: volume
              source: dev_data_volume
              target: /workspace/data
        environment:
            LANG: ja_JP.UTF-8
            LANGUAGE: ja_JP:ja
            LC_ALL: ja_JP.UTF-8
            TZ: JST-9
            DEBUG: 1
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]
        depends_on:
            - devcontainer
        restart: "no"

    # 開発作業用コンテナ
    devcontainer:
        build:
            context: ../
            dockerfile: .devcontainer/Dockerfile
        tty: true
        volumes:
            - type: bind 
              source: ../
              target: /workspace/
            - type: volume
              source: dev_data_volume
              target: /workspace/data
            - type: volume
              source: dev_npm_volume
              target: /workspace/src/frontend/node_modules
        environment:
            LANG: ja_JP.UTF-8
            LANGUAGE: ja_JP:ja
            LC_ALL: ja_JP.UTF-8
            TZ: JST-9
            DEBUG: 1
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]

volumes:
    # データファイル用ボリューム
    dev_data_volume:
    # node_modules用ボリューム DevContainerとFrontendで共有するためボリューム化
    dev_npm_volume: